### ISSUE TITLE
Stuff we need.

### ISSUE THREAD

**Issue by YoungFlyme** [Henningstone/HMod#3]
In this issue i will collect all missing features of lua ^^.

- [ ] CNetEvent's (Like explosions)
- [x] Chat Management (720c12320fdd9e9ee0dab643df938f42bac1a362)
- [ ] Config Vars
- [ ] Tuning Vars

If you miss some features too, write it in here! I will collect them and update this Issue.

**Comment by Henningstone** [comment]
> In this issue i will collect all […]

Bad concept; that's not what issues are meant for. Do that on a piece of paper if you wish, but please open a new issue for every single thing you want to have added so we can organize them (i.e. assign priorities, put them onto the Kanban board or whatever) and keep track of what should be done when and in which order.

I've split this issue up into multiple issues that are referenced above this comment.

Direct access to CNetEvents is not planned because you'd also have to have access to the server's networking, which imho is too low level already for a modding framework. Methods that trigger net events will of course be added to the api, though, and some are even in there already.
